# Generated by Django 3.1 on 2020-10-18 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_paper', '0004_auto_20201017_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dicty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_paper.dicty'),
        ),
    ]
