# Generated by Django 3.1 on 2020-10-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_paper', '0005_auto_20201018_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Dicty',
        ),
    ]
