# Generated by Django 3.1 on 2020-10-18 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_paper', '0007_modules'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Modules',
            new_name='Module',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='moduleID',
            new_name='moduleId',
        ),
    ]
