# Generated by Django 3.1 on 2020-10-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_paper', '0011_auto_20201018_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_ans',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(default=dict),
        ),
    ]
