# Generated by Django 3.1 on 2020-10-19 16:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_paper', '0012_auto_20201018_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_ans',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1), default=list, size=None),
        ),
    ]
