# Generated by Django 3.1 on 2020-10-20 16:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_paper', '0015_auto_20201020_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_ans',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), default=list, size=8),
        ),
    ]
